CREATE TABLE `com_com_identificationdata` (
                                              `ID` decimal(11,0) NOT NULL,
                                              `ECID` decimal(11,0) NOT NULL,
                                              `IDENTIFICATIONTYPECODE` decimal(5,0) NOT NULL,
                                              `IDENTIFICATION` char(50) NOT NULL,
                                              `BEGINDATE` date DEFAULT NULL,
                                              `ENDDATE` date DEFAULT NULL,
                                              `TERRITORYID` decimal(11,0) DEFAULT NULL,
                                              `ISSUER` char(200) DEFAULT NULL,
                                              `ISSUERTYPECODE` decimal(5,0) DEFAULT NULL,
                                              `IDENTIFICATIONQI` decimal(1,0) DEFAULT NULL,
                                              `BEGINDATEQI` decimal(1,0) DEFAULT NULL,
                                              `ENDDATEQI` decimal(1,0) DEFAULT NULL,
                                              `ISSUERQI` decimal(1,0) DEFAULT NULL,
                                              `FRESHNESSDATE` timestamp(6) NULL DEFAULT NULL,
                                              `CREATEDATE` timestamp(6) NOT NULL DEFAULT current_timestamp(6),
                                              `UPDATEDATE` timestamp(6) NOT NULL DEFAULT current_timestamp(6),
                                              `VERSION` decimal(11,0) NOT NULL,
                                              `USERNAME` char(50) DEFAULT NULL,
                                              PRIMARY KEY (`ID`),
                                              UNIQUE KEY `IDENTIFICATIONDATA_PK` (`ID`),
                                              UNIQUE KEY `IDENTIFICATIONDATA_IDX3` (`ID`,`ECID`),
                                              KEY `IDENTIFICATIONDATA_IDX1` (`ECID`),
                                              KEY `IDENTIFICATIONDATA_IDX2` (`ECID`,`IDENTIFICATIONTYPECODE`,`IDENTIFICATION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `com_com_legalperson` (
                                       `ID` decimal(11,0) NOT NULL,
                                       `ECID` decimal(11,0) NOT NULL,
                                       `DENOMINATION` char(200) DEFAULT NULL,
                                       `LEGALFORMCODE` decimal(5,0) DEFAULT NULL,
                                       `ORGANIZATIONTYPECODE` decimal(5,0) DEFAULT NULL,
                                       `PUBLICAUTHORITYTYPECODE` decimal(5,0) DEFAULT NULL,
                                       `DENOMINATIONQI` decimal(1,0) DEFAULT NULL,
                                       `LEGALFORMCODEQI` decimal(1,0) DEFAULT NULL,
                                       `ORGANIZATIONTYPECODEQI` decimal(1,0) DEFAULT NULL,
                                       `PUBLICAUTHORITYTYPECODEQI` decimal(1,0) DEFAULT NULL,
                                       `FRESHNESSDATE` timestamp(6) NULL DEFAULT NULL,
                                       `CREATEDATE` timestamp(6) NOT NULL DEFAULT current_timestamp(6),
                                       `UPDATEDATE` timestamp(6) NOT NULL DEFAULT current_timestamp(6),
                                       `VERSION` decimal(11,0) NOT NULL,
                                       `USERNAME` char(50) DEFAULT NULL,
                                       PRIMARY KEY (`ID`),
                                       UNIQUE KEY `LEGALPERSON_PK` (`ID`),
                                       UNIQUE KEY `LEGALPERSON_IDX1` (`ECID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `com_com_masterdata` (
                                      `ECID` decimal(11,0) NOT NULL,
                                      `COMPANYID` decimal(11,0) DEFAULT NULL,
                                      `NOMINATIVE` char(200) DEFAULT NULL,
                                      `PERSONTYPECODE` decimal(5,0) DEFAULT NULL,
                                      `VERSIONDATE` date DEFAULT NULL,
                                      `UCID` char(20) DEFAULT NULL,
                                      `NOMINATIVEQI` decimal(1,0) DEFAULT NULL,
                                      `PERSONTYPECODEQI` decimal(1,0) DEFAULT NULL,
                                      `UCIDQI` decimal(1,0) DEFAULT NULL,
                                      `COMPLETENESSINDEX` decimal(5,2) DEFAULT NULL,
                                      `QUALITYINDEX` decimal(5,2) DEFAULT NULL,
                                      `FRESHNESSDATE` timestamp(6) NULL DEFAULT NULL,
                                      `CREATEDATE` timestamp(6) NOT NULL DEFAULT current_timestamp(6),
                                      `UPDATEDATE` timestamp(6) NOT NULL DEFAULT current_timestamp(6),
                                      `VERSION` decimal(11,0) NOT NULL,
                                      `USERNAME` char(50) DEFAULT NULL,
                                      PRIMARY KEY (`ECID`),
                                      UNIQUE KEY `MASTERDATA_PK` (`ECID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `com_com_naturalperson` (
                                         `ID` decimal(11,0) NOT NULL,
                                         `ECID` decimal(11,0) NOT NULL,
                                         `NAME` char(200) DEFAULT NULL,
                                         `SURNAME` char(200) DEFAULT NULL,
                                         `GENDERCODE` decimal(5,0) DEFAULT NULL,
                                         `PERSONALTITLECODE` decimal(5,0) DEFAULT NULL,
                                         `MARITALSTATUSCODE` decimal(5,0) DEFAULT NULL,
                                         `QUALIFICATIONLEVEL1CODE` decimal(5,0) DEFAULT NULL,
                                         `QUALIFICATIONLEVEL2CODE` decimal(5,0) DEFAULT NULL,
                                         `QUALIFICATIONLEVEL3CODE` decimal(5,0) DEFAULT NULL,
                                         `NAMEQI` decimal(1,0) DEFAULT NULL,
                                         `SURNAMEQI` decimal(1,0) DEFAULT NULL,
                                         `GENDERCODEQI` decimal(1,0) DEFAULT NULL,
                                         `PERSONALTITLECODEQI` decimal(1,0) DEFAULT NULL,
                                         `MARITALSTATUSCODEQI` decimal(1,0) DEFAULT NULL,
                                         `QUALIFICATIONQI` decimal(1,0) DEFAULT NULL,
                                         `FRESHNESSDATE` timestamp(6) NOT NULL DEFAULT current_timestamp(6),
                                         `CREATEDATE` timestamp(6) NOT NULL DEFAULT current_timestamp(6),
                                         `UPDATEDATE` timestamp(6) NOT NULL DEFAULT current_timestamp(6),
                                         `VERSION` decimal(11,0) NOT NULL,
                                         `USERNAME` char(50) DEFAULT NULL,
                                         PRIMARY KEY (`ID`),
                                         UNIQUE KEY `NATURALPERSON_PK` (`ID`),
                                         UNIQUE KEY `NATURALPERSON_IDX1` (`ECID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `com_meta_territory` (
                                      `id` int(11) NOT NULL,
                                      `additionalcode1` varchar(255) DEFAULT NULL,
                                      `additionalcode2` varchar(255) DEFAULT NULL,
                                      `additionalcode3` varchar(255) DEFAULT NULL,
                                      `additionalcode4` varchar(255) DEFAULT NULL,
                                      `additionalcode5` varchar(255) DEFAULT NULL,
                                      `address` varchar(255) DEFAULT NULL,
                                      `adminarea1` varchar(255) DEFAULT NULL,
                                      `adminarea1code` varchar(255) DEFAULT NULL,
                                      `adminarea1legacyid` int(11) DEFAULT NULL,
                                      `adminarea2` varchar(255) DEFAULT NULL,
                                      `adminarea2code` varchar(255) DEFAULT NULL,
                                      `adminarea2legacyid` int(11) DEFAULT NULL,
                                      `adminarea3` varchar(255) DEFAULT NULL,
                                      `adminarea3code` varchar(255) DEFAULT NULL,
                                      `adminarea3legacyid` int(11) DEFAULT NULL,
                                      `adminarea4` varchar(255) DEFAULT NULL,
                                      `adminarea4code` varchar(255) DEFAULT NULL,
                                      `adminarea4legacyid` int(11) DEFAULT NULL,
                                      `adminarea5` varchar(255) DEFAULT NULL,
                                      `adminarea5code` varchar(255) DEFAULT NULL,
                                      `adminarea5legacyid` int(11) DEFAULT NULL,
                                      `adminareaqi` decimal(19,2) DEFAULT NULL,
                                      `adminlevel` int(11) DEFAULT NULL,
                                      `altitude` decimal(19,2) DEFAULT NULL,
                                      `coordinateqi` decimal(19,2) DEFAULT NULL,
                                      `coordinatereference` varchar(255) DEFAULT NULL,
                                      `createdate` datetime DEFAULT NULL,
                                      `housenumber` varchar(255) DEFAULT NULL,
                                      `latitude` decimal(19,2) DEFAULT NULL,
                                      `longitude` decimal(19,2) DEFAULT NULL,
                                      `matchingcode` varchar(255) DEFAULT NULL,
                                      `postalcode` varchar(255) DEFAULT NULL,
                                      `postalcodeqi` decimal(19,2) DEFAULT NULL,
                                      `streetname` varchar(255) DEFAULT NULL,
                                      `streetnamelegacyid` int(11) DEFAULT NULL,
                                      `streetqi` decimal(19,2) DEFAULT NULL,
                                      `streettype` varchar(255) DEFAULT NULL,
                                      `streettypelegacyid` int(11) DEFAULT NULL,
                                      `updatedate` datetime DEFAULT NULL,
                                      `username` varchar(255) DEFAULT NULL,
                                      `version` int(11) DEFAULT NULL,
                                      PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `com_com_pridentifications` (
                                             `legacyidentificationid` int(11) NOT NULL,
                                             `createdate` datetime DEFAULT NULL,
                                             `entityid` int(11) DEFAULT NULL,
                                             `id` int(11) DEFAULT NULL,
                                             `idversion` int(11) DEFAULT NULL,
                                             `productroleid` int(11) DEFAULT NULL,
                                             `updatedate` datetime DEFAULT NULL,
                                             `username` varchar(255) DEFAULT NULL,
                                             `version` int(11) DEFAULT NULL,
                                             PRIMARY KEY (`legacyidentificationid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `com_com_postaladdresses` (
                                           `id` int(11) NOT NULL,
                                           `additionaldata1` varchar(255) DEFAULT NULL,
                                           `additionaldata2` varchar(255) DEFAULT NULL,
                                           `additionaldata3` varchar(255) DEFAULT NULL,
                                           `additionaldata4` varchar(255) DEFAULT NULL,
                                           `additionaldata5` varchar(255) DEFAULT NULL,
                                           `createdate` datetime DEFAULT NULL,
                                           `ecid` int(11) DEFAULT NULL,
                                           `freshnessdate` datetime DEFAULT NULL,
                                           `territoryid` int(11) DEFAULT NULL,
                                           `typecode` int(11) DEFAULT NULL,
                                           `typecodeqi` decimal(19,2) DEFAULT NULL,
                                           `updatedate` datetime DEFAULT NULL,
                                           `usagecode` int(11) DEFAULT NULL,
                                           `usagecodeqi` decimal(19,2) DEFAULT NULL,
                                           `username` varchar(255) DEFAULT NULL,
                                           `version` int(11) DEFAULT NULL,
                                           PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `pgtitolo` (
                            `IDTITOLO` decimal(18,0) NOT NULL,
                            `BTITOLOAPPORTO` decimal(1,0) DEFAULT 0,
                            `ESTATOPAGAMENTO` decimal(18,0) DEFAULT NULL,
                            `DATTILEGALI` date DEFAULT NULL,
                            `NIMPORTOPROVV` decimal(17,3) DEFAULT NULL,
                            `CNUMPOLIZZA` varchar(25) DEFAULT NULL,
                            `BPROPOSTA` decimal(1,0) DEFAULT 0,
                            `ESTATO` decimal(18,0) DEFAULT NULL,
                            `NIMPORTO` decimal(17,3) DEFAULT NULL,
                            `DSCADENZA` date DEFAULT NULL,
                            `BINCASSO100` decimal(1,0) DEFAULT 0,
                            `DEFFETTO` date DEFAULT NULL,
                            `NIMPORTOTOTALE` decimal(17,3) DEFAULT NULL,
                            `ECARICOSOTTOTIPO` decimal(18,0) DEFAULT NULL,
                            `NAPPENDICE` decimal(5,0) DEFAULT NULL,
                            `CNUMPROPOSTA` varchar(16) DEFAULT NULL,
                            `DEMISSIONE` date DEFAULT NULL,
                            `DBOLLATO` date DEFAULT NULL,
                            `ECARICOTIPO` decimal(18,0) DEFAULT NULL,
                            `DCARICO` date DEFAULT NULL,
                            `IDCOMPAGNIA` decimal(18,0) DEFAULT NULL,
                            `IDNODO` decimal(18,0) DEFAULT NULL,
                            `IDCAUSALE` decimal(18,0) DEFAULT NULL,
                            `IDDIVISA` decimal(5,0) DEFAULT NULL,
                            `IDCONTORB` decimal(18,0) DEFAULT NULL,
                            `IDPAGAMENTO` decimal(18,0) DEFAULT NULL,
                            `IDPRODOTTO` decimal(10,0) DEFAULT NULL,
                            `IDCONTRAENTE` decimal(18,0) DEFAULT NULL,
                            `IDASSICURATO` decimal(18,0) DEFAULT NULL,
                            `BSTORNATO` decimal(1,0) DEFAULT 0,
                            `IDMOTIVOANNULLO` decimal(18,0) DEFAULT NULL,
                            `BSUPPLETIVO` decimal(1,0) DEFAULT 0,
                            `BINVIATOCOGE` decimal(1,0) DEFAULT 0,
                            `IDGRUPPOTITOLI` decimal(18,0) DEFAULT NULL,
                            `IDTITOLOCOLLEGATO` decimal(18,0) DEFAULT NULL,
                            `BGRUPPOTITOLI` decimal(1,0) DEFAULT 0,
                            `IDNODOSECONDARIO` decimal(18,0) DEFAULT NULL,
                            `IDFILIALE` decimal(18,0) DEFAULT NULL,
                            `BPRINCIPALE` decimal(1,0) DEFAULT 0,
                            `BPROVVPREC` decimal(1,0) DEFAULT 0,
                            `ETIPOCOASS` decimal(18,0) DEFAULT NULL,
                            `NSOPRAVVENIENZA` decimal(17,3) DEFAULT NULL,
                            `IDPRODUTTORE` decimal(18,0) DEFAULT NULL,
                            `CNUMSINISTRO` varchar(25) DEFAULT NULL,
                            `CNUMRECUPERO` varchar(20) DEFAULT NULL,
                            `IDUSERINS` decimal(18,0) DEFAULT NULL,
                            `IDUSERMOD` decimal(18,0) DEFAULT NULL,
                            `DINS` timestamp(6) NULL DEFAULT NULL,
                            `DMOD` timestamp(6) NULL DEFAULT NULL,
                            `CPROVRESCONTRAENTE` varchar(4) DEFAULT NULL,
                            `DNOTIFICA` timestamp(6) NULL DEFAULT NULL,
                            `IDSOGGETTORECUPERO` decimal(18,0) DEFAULT NULL,
                            `BALTRIONERI` decimal(1,0) DEFAULT 0,
                            `NIMPORTOTOTQUOTE` decimal(17,3) DEFAULT NULL,
                            `NPERCNOSTRA` decimal(6,2) DEFAULT NULL,
                            `DCOMPETENZARIASS` date DEFAULT NULL,
                            `IDNODOGESTIONE` decimal(18,0) DEFAULT NULL,
                            `BEMESSODIREZIONE` decimal(1,0) DEFAULT 0,
                            `NIMPORTOSPESE` decimal(17,3) DEFAULT NULL,
                            `IDNODOINCASSO` decimal(18,0) DEFAULT NULL,
                            `DINCASSO` date DEFAULT NULL,
                            `BMIGRATO` decimal(1,0) DEFAULT 0,
                            `CNOTE` varchar(2000) DEFAULT NULL,
                            `BRIPRISTINATO` decimal(1,0) DEFAULT 0,
                            `IDTITOLOSTORNATO` decimal(18,0) DEFAULT NULL,
                            `BRIASS` decimal(1,0) DEFAULT 0,
                            `DESIGIBILITA` date DEFAULT NULL,
                            `BANNULLOCONTABILE` decimal(1,0) DEFAULT 0,
                            `CCODICEGESTIONE` varchar(6) DEFAULT NULL,
                            `DTRASFCONT` timestamp(6) NULL DEFAULT NULL,
                            `NIMPORTOFONDO` decimal(17,3) DEFAULT NULL,
                            `CNUMLIQUID` varchar(20) DEFAULT NULL,
                            `NLPSIMPORTO` decimal(17,3) DEFAULT NULL,
                            `CDESCAPPENDICE` varchar(100) DEFAULT NULL,
                            `DSTORNO` date DEFAULT NULL,
                            `ETIPORAPPEL` decimal(18,0) DEFAULT NULL,
                            `ETIPOINCASSO` decimal(18,0) DEFAULT NULL,
                            `DANNULLO` date DEFAULT NULL,
                            `EMODINCASSOCOASS` decimal(18,0) DEFAULT NULL,
                            `BRISERVAPREMI` decimal(1,0) DEFAULT 0,
                            `BESENTEIMPOSTE` decimal(1,0) DEFAULT 0,
                            `ECATEGORIAPRODOTTO` decimal(18,0) DEFAULT NULL,
                            `DEFFETTIVOINCASSO` date DEFAULT NULL,
                            `BVITA` decimal(1,0) DEFAULT 0,
                            `BAUTOESITATO` decimal(1,0) DEFAULT 0,
                            `DSISTEMAANNULLO` date DEFAULT NULL,
                            `DDATACARICOSTORNO` date DEFAULT NULL,
                            `IDFRAZ` decimal(5,0) DEFAULT NULL,
                            `DDATAEFFETTOPOL` date DEFAULT NULL,
                            `DDATASCADENZAPOL` date DEFAULT NULL,
                            `ETIPORISERVAPREMI` decimal(18,0) DEFAULT NULL,
                            `DDATACAMBIO` date DEFAULT NULL,
                            `NIMPTASSOCAMBIO` decimal(20,6) DEFAULT 1.000000,
                            `IDCONTRAENTELOCK` decimal(18,0) DEFAULT NULL,
                            `IDASSICURATOLOCK` decimal(18,0) DEFAULT NULL,
                            `CSIGLANAZIONE` varchar(3) DEFAULT NULL,
                            `CPROVTASSAZIONE` varchar(2) DEFAULT NULL,
                            `IDMEANPAYMENTDATA` decimal(18,0) DEFAULT NULL,
                            `NPARTIALCOLLAMOUNT` decimal(17,3) DEFAULT NULL,
                            `EREVERSEREASONDDO` decimal(18,0) DEFAULT NULL,
                            `EPROVENIENZA` decimal(18,0) DEFAULT NULL,
                            `ETIPODOCIVA` decimal(18,0) DEFAULT 0,
                            `CNUMDOCIVA` varchar(25) DEFAULT NULL,
                            `CNUMPROTIVA` varchar(25) DEFAULT NULL,
                            `DINVOICE` date DEFAULT NULL,
                            `CNUMDOCIVAANN` varchar(25) DEFAULT NULL,
                            `CNUMPROTIVAANN` varchar(25) DEFAULT NULL,
                            `IDCONTEXT` decimal(18,0) DEFAULT NULL,
                            `ECREDITCONTROL` decimal(18,0) DEFAULT NULL,
                            `ECOMMISSIONSTATUS` decimal(18,0) DEFAULT NULL,
                            `ECASHABLE` decimal(18,0) DEFAULT 4,
                            `IDPAYERLOCK` decimal(18,0) DEFAULT NULL,
                            `NEXTRACOMMNET` decimal(17,3) DEFAULT NULL,
                            `NEXTRACOMMFEE` decimal(17,3) DEFAULT NULL,
                            `EMARKER` decimal(18,0) DEFAULT NULL,
                            `CMASTERPOLICY` varchar(25) DEFAULT NULL,
                            PRIMARY KEY (`IDTITOLO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `pcversione` (
                              `IDPOLIZZA` decimal(18,0) NOT NULL,
                              `NVERINIZIO` decimal(18,0) NOT NULL,
                              `NVERFINE` decimal(18,0) NOT NULL,
                              `DSCADREGOLAZIONE` date DEFAULT NULL,
                              `BREGOLAZIONE` decimal(1,0) DEFAULT NULL,
                              `BINDICIZZAZIONE` decimal(1,0) DEFAULT NULL,
                              `IDPRODUTTORE` decimal(18,0) DEFAULT NULL,
                              `IDPVGESTIONE` decimal(18,0) NOT NULL,
                              `IDCONVENZIONE` decimal(5,0) DEFAULT NULL,
                              `NPERCNOSTRA` decimal(6,2) DEFAULT NULL,
                              `ETIPOCOASS` decimal(5,0) NOT NULL,
                              `DEFFETTOPOLIZZA` date DEFAULT NULL,
                              `DSCADENZAPOLIZZA` date DEFAULT NULL,
                              `IDFRAZ` decimal(5,0) DEFAULT NULL,
                              `NFREQRESCINDIBILTA` decimal(5,0) DEFAULT NULL,
                              `IDFILIALE` decimal(18,0) DEFAULT NULL,
                              `IDTIPOREGPREMIO` decimal(5,0) DEFAULT NULL,
                              `NGIORNIREGOLAZIONE` decimal(5,0) DEFAULT NULL,
                              `IDRECAPITO` decimal(18,0) DEFAULT NULL,
                              `DTARIFFA` date DEFAULT NULL,
                              `CORAEFFETTOCOP` varchar(5) DEFAULT NULL,
                              `BINCASSOCOASS100` decimal(1,0) DEFAULT NULL,
                              `NVALOREINDICE` decimal(6,2) DEFAULT NULL,
                              `IDFRAZPROROGA` decimal(5,0) DEFAULT NULL,
                              `IDFRAZREGOLAZ` decimal(5,0) DEFAULT NULL,
                              `DRESCINDIBILITA` date DEFAULT NULL,
                              `BRIASS` decimal(1,0) DEFAULT NULL,
                              `NGGPREMIO` decimal(5,0) DEFAULT NULL,
                              `NPERCINTFRAZ` decimal(6,2) DEFAULT NULL,
                              `NPROROGHETOTALI` decimal(5,0) DEFAULT NULL,
                              `BRIMBORSOIMPOSTE` decimal(1,0) DEFAULT NULL,
                              `NDIRITTIPR` decimal(17,3) DEFAULT NULL,
                              `NDIRITTIRS` decimal(17,3) DEFAULT NULL,
                              `NPERCPROVVDIRITTI` decimal(6,2) DEFAULT NULL,
                              `IDVERSIONE` decimal(5,0) DEFAULT NULL,
                              `BTACITORINNOVO` decimal(1,0) DEFAULT NULL,
                              `BPROROGA` decimal(1,0) DEFAULT NULL,
                              `BVINCOLO` decimal(1,0) DEFAULT NULL,
                              `BRISCHIOCOMUNE` decimal(1,0) DEFAULT NULL,
                              `BCOASSINDIRETTA` decimal(1,0) DEFAULT NULL,
                              `BSECONDORISCHIO` decimal(1,0) DEFAULT NULL,
                              `BCOMPAGNIEESTERE` decimal(1,0) DEFAULT NULL,
                              `IDTIPOINDICIZZ` decimal(5,0) DEFAULT NULL,
                              `BLPS` decimal(1,0) DEFAULT NULL,
                              `EPLAFONAPREMIO` decimal(5,0) DEFAULT NULL,
                              `BDIRITTI` decimal(1,0) DEFAULT NULL,
                              `BCOMPLEMENTARE` decimal(1,0) DEFAULT NULL,
                              `EREGPROVVATTIVE` decimal(5,0) DEFAULT NULL,
                              `EREGPROVVPASSIVE` decimal(5,0) DEFAULT NULL,
                              `DSCADREGOLAZRICDOC` date DEFAULT NULL,
                              `NPREMIOMINREGOLAZ` decimal(17,3) DEFAULT NULL,
                              `NPERCPREMIOREGOLAZ` decimal(6,2) DEFAULT NULL,
                              `DRICDOCREGOLAZ` date DEFAULT NULL,
                              `NPERCPREMINREGOLAZ` decimal(6,2) DEFAULT NULL,
                              `NPERCSCONTO` decimal(6,2) DEFAULT NULL,
                              `NPERCSCONTO2` decimal(6,2) DEFAULT NULL,
                              `NIMPSCONTO` decimal(17,3) DEFAULT NULL,
                              `NIMPSCONTO2` decimal(17,3) DEFAULT NULL,
                              `EMODOINSERSCONTO` decimal(5,0) DEFAULT NULL,
                              `EMODOINSERSCONTO2` decimal(5,0) DEFAULT NULL,
                              `BINTERROMPICATENA` decimal(1,0) DEFAULT NULL,
                              `CCODICESEDE` varchar(18) DEFAULT NULL,
                              `NPERCSCONTOEFF` decimal(6,2) DEFAULT NULL,
                              `NIMPSCONTOEFF` decimal(17,3) DEFAULT NULL,
                              `NIMPTOTIMPONIBILE` decimal(17,3) DEFAULT NULL,
                              `NIMPTOTLORDO` decimal(17,3) DEFAULT NULL,
                              `CCODICECAMPAGNA` varchar(6) DEFAULT NULL,
                              `DCAMBIO` date DEFAULT NULL,
                              `NTASSOCAMBIO` decimal(18,6) DEFAULT NULL,
                              `NPERCACC` decimal(6,2) DEFAULT NULL,
                              `NIMPTOTNETTO` decimal(17,3) DEFAULT NULL,
                              `NIMPTOTINTFRAZ` decimal(17,3) DEFAULT NULL,
                              `NIMPTOTIMPOSTE` decimal(17,3) DEFAULT NULL,
                              `NIMPSSN` decimal(17,3) DEFAULT NULL,
                              `IDCOUPON` decimal(18,0) DEFAULT NULL,
                              `NGGMORA` decimal(5,0) DEFAULT NULL,
                              `EPROVENIENZAPROP` decimal(18,0) DEFAULT NULL,
                              `IDADDRESS` decimal(18,0) DEFAULT NULL,
                              `IDPARTNER` decimal(18,0) DEFAULT NULL,
                              `IDPARTNERAGENCY` decimal(18,0) DEFAULT NULL,
                              PRIMARY KEY (`IDPOLIZZA`,`NVERINIZIO`,`NVERFINE`,`IDPVGESTIONE`,`ETIPOCOASS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `pcpolizzaruolo` (
                                  `IDPOLIZZA` decimal(18,0) NOT NULL,
                                  `IDRUOLO` decimal(18,0) NOT NULL,
                                  `NVERINIZIO` decimal(18,0) NOT NULL,
                                  `NVERFINE` decimal(18,0) DEFAULT NULL,
                                  `BBENE` decimal(1,0) DEFAULT NULL,
                                  PRIMARY KEY (`IDPOLIZZA`,`IDRUOLO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `pcpolizza` (
                             `IDPOLIZZA` decimal(18,0) NOT NULL,
                             `EMOTIVOANNULPROP` decimal(5,0) DEFAULT NULL,
                             `DEMISSIONE` date DEFAULT NULL,
                             `EMOTIVOCREAZIONE` decimal(5,0) NOT NULL,
                             `CDESCRIZIONE` varchar(100) NOT NULL,
                             `BPOLIZZA` decimal(1,0) NOT NULL,
                             `CNUMPROPOSTA` varchar(16) DEFAULT NULL,
                             `CNUMPOLIZZA` varchar(25) DEFAULT NULL,
                             `DFINEVALPROP` date NOT NULL,
                             `IDPRODOTTO` decimal(10,0) DEFAULT NULL,
                             `IDDIVISA` decimal(5,0) NOT NULL,
                             `IDPVPRODUZIONE` decimal(18,0) NOT NULL,
                             `IDUSERINS` decimal(18,0) NOT NULL,
                             `DINS` timestamp(6) NULL DEFAULT NULL,
                             `IDUSERAGG` decimal(18,0) NOT NULL,
                             `DAGG` timestamp(6) NULL DEFAULT NULL,
                             `DANNULLAMENTO` date DEFAULT NULL,
                             `BACCORPARATA` decimal(1,0) DEFAULT NULL,
                             `DEFFETTOORIGINALE` date DEFAULT NULL,
                             `BPROVVPREC` decimal(1,0) DEFAULT NULL,
                             `DPROPOSTA` date DEFAULT NULL,
                             `EMOTIVOSOST` decimal(5,0) DEFAULT NULL,
                             `BDANNI` decimal(1,0) NOT NULL,
                             `BVITA` decimal(1,0) NOT NULL,
                             `DSCADENZAORIGINALE` date DEFAULT NULL,
                             `BMIGRATA` decimal(1,0) DEFAULT NULL,
                             `EUSOIMPOSTA` decimal(5,0) DEFAULT NULL,
                             `IDCOMPAGNIA` decimal(18,0) DEFAULT NULL,
                             `DBLOCCOQUIET` date DEFAULT NULL,
                             `CCODICERAMOTECNICO` varchar(6) DEFAULT NULL,
                             `DTRASFLEGALE` date DEFAULT NULL,
                             `DTRASFAGENZIA` date DEFAULT NULL,
                             `CNUMAPPLICAZIONE` varchar(25) DEFAULT NULL,
                             `ETIPOPOLIZZA` decimal(5,0) DEFAULT NULL,
                             `BMODELLO` decimal(1,0) DEFAULT NULL,
                             `NMAXVERSIONE` decimal(18,0) DEFAULT NULL,
                             `ECATEGORIA` decimal(5,0) DEFAULT NULL,
                             `DEFFETTOCORRENTE` date DEFAULT NULL,
                             `DSCADENZACORRENTE` date DEFAULT NULL,
                             `IDPVGESTCORRENTE` decimal(18,0) DEFAULT NULL,
                             `IDMOTSOSTITUZIONE` decimal(18,0) DEFAULT NULL,
                             `DUSCITAESPOSIZIONE` date DEFAULT NULL,
                             `EPROVENIENZA` decimal(5,0) DEFAULT NULL,
                             `NGGDISDETTA` decimal(5,0) DEFAULT NULL,
                             `DINVIOCOMANNULLO` date DEFAULT NULL,
                             `IDPASSAUTORIZZ` decimal(18,0) DEFAULT NULL,
                             `CNOTE` varchar(255) DEFAULT NULL,
                             `DBLOCCOOPERATIVITA` date DEFAULT NULL,
                             `CNUMLOTTO` varchar(25) DEFAULT NULL,
                             `CNUMFINANZIAMENTO` varchar(25) DEFAULT NULL,
                             `CNUMQUOTE` varchar(25) DEFAULT NULL,
                             `IDCONTEXT` decimal(18,0) DEFAULT NULL,
                             `CLOCKCODE` varchar(6) DEFAULT NULL,
                             `NCPRATIO` decimal(18,6) DEFAULT NULL,
                             `DUPDCPRATIO` date DEFAULT NULL,
                             `BPRIVACYCOMMERCIALE` decimal(1,0) DEFAULT NULL,
                             PRIMARY KEY (`IDPOLIZZA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `pcmovimento` (
                               `IDMOVIMENTO` decimal(18,0) NOT NULL,
                               `NVERSIONE` decimal(18,0) NOT NULL,
                               `BTEMPORANEO` decimal(1,0) NOT NULL,
                               `CDESCRIZIONE` varchar(100) NOT NULL,
                               `DEFFETTO` date NOT NULL,
                               `DSCADENZA` date DEFAULT NULL,
                               `DEMISSIONE` date NOT NULL,
                               `IDPOLIZZA` decimal(18,0) NOT NULL,
                               `IDCAUSALE` decimal(18,0) NOT NULL,
                               `IDGRUPPOTITOLI` decimal(18,0) DEFAULT NULL,
                               `NNUMEROAPPENDICE` decimal(5,0) DEFAULT NULL,
                               `CNOTE` varchar(255) DEFAULT NULL,
                               `ESTATO` decimal(18,0) DEFAULT NULL,
                               `IDUSER` decimal(18,0) DEFAULT NULL,
                               `DOPERAZIONE` timestamp(6) NULL DEFAULT NULL,
                               `BANNULLATO` decimal(1,0) DEFAULT NULL,
                               `ESTATOAUT` decimal(5,0) DEFAULT NULL,
                               `CORAEFFETTO` varchar(5) DEFAULT NULL,
                               `BMIGRATO` decimal(1,0) DEFAULT NULL,
                               `ECATEGORIA` decimal(5,0) DEFAULT NULL,
                               `ESOTTOSTATO` decimal(18,0) DEFAULT NULL,
                               `IDCOMPAGNIA` decimal(18,0) DEFAULT NULL,
                               `ESTATOREGOLAZIONE` decimal(18,0) DEFAULT NULL,
                               `IDMOVREGOLAZIONE` decimal(18,0) DEFAULT NULL,
                               `DSTORNO` date DEFAULT NULL,
                               `IDMOVANNULLATO` decimal(18,0) DEFAULT NULL,
                               `BAUTODEROGATO` decimal(1,0) DEFAULT NULL,
                               `EAPPFEDFISCALE` decimal(18,0) DEFAULT NULL,
                               `EPROVENIENZA` decimal(18,0) DEFAULT NULL,
                               `IDCURRENCY` decimal(5,0) DEFAULT NULL,
                               `DEXCHANGE` date DEFAULT NULL,
                               `NEXCHANGERATE` decimal(18,6) DEFAULT NULL,
                               `DCARICO` date DEFAULT NULL,
                               `DCARICOSTORNO` date DEFAULT NULL,
                               `IDCAUSALESTORNO` decimal(18,0) DEFAULT NULL,
                               `BSUPPLETTIVO` decimal(1,0) DEFAULT NULL,
                               `TEMISSIONEMOV` timestamp(6) NULL DEFAULT NULL,
                               PRIMARY KEY (`IDMOVIMENTO`,`NVERSIONE`,`BTEMPORANEO`,`CDESCRIZIONE`,`DEFFETTO`,`DEMISSIONE`,`IDPOLIZZA`,`IDCAUSALE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `pasoggettolock` (
                                  `IDSOGGETTOLOCK` decimal(18,0) NOT NULL,
                                  `IDSOGGETTO` decimal(18,0) DEFAULT NULL,
                                  `DMODIFICA` date DEFAULT NULL,
                                  `IDDATISINGOLI` decimal(18,0) DEFAULT NULL,
                                  `IDRESIDENZA` decimal(18,0) DEFAULT NULL,
                                  `IDUSER` decimal(18,0) DEFAULT NULL,
                                  `DCHIUSURA` date DEFAULT NULL,
                                  `TINS` timestamp(6) NULL DEFAULT NULL,
                                  `IDRESIDENCE` decimal(18,0) DEFAULT NULL,
                                  PRIMARY KEY (`IDSOGGETTOLOCK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `pasoggetto` (
                              `IDSOGGETTO` decimal(18,0) NOT NULL,
                              `IDCOMPAGNIA` decimal(18,0) DEFAULT NULL,
                              `EGIURIDICOFISICO` decimal(5,0) DEFAULT NULL,
                              `ETIPOSOGGETTO` decimal(5,0) DEFAULT NULL,
                              `IDDATISINGOLI` decimal(18,0) NOT NULL,
                              `IDRESIDENZA` decimal(18,0) DEFAULT NULL,
                              `CCODICEFISCALE` varchar(16) DEFAULT NULL,
                              `ESESSO` decimal(5,0) DEFAULT NULL,
                              `DNASCITA` date DEFAULT NULL,
                              `CNAZIONENASCITA` varchar(3) DEFAULT NULL,
                              `CPROVINCIANASCITA` varchar(4) DEFAULT NULL,
                              `ECANALEACQ` decimal(5,0) DEFAULT NULL,
                              `IDUSERINS` decimal(18,0) DEFAULT NULL,
                              `IDUSERAGG` decimal(18,0) DEFAULT NULL,
                              `TAGG` timestamp(6) NULL DEFAULT NULL,
                              `TINS` timestamp(6) NULL DEFAULT NULL,
                              `IDTITOLOONORIFICO` decimal(18,0) DEFAULT NULL,
                              `BESENZIONEIMPOSTE` decimal(1,0) DEFAULT NULL,
                              `IDULTIMAFOTO` decimal(18,0) DEFAULT NULL,
                              `ETIPOANAGRAFICA` decimal(5,0) DEFAULT NULL,
                              `CLOCALITANASCITA` varchar(50) DEFAULT NULL,
                              `DAPERTURASOCIETA` date DEFAULT NULL,
                              `CNUMCARPETTA` varchar(18) DEFAULT NULL,
                              `BMIGRATO` decimal(1,0) DEFAULT NULL,
                              `IDTITOLOSTUDIO` decimal(18,0) DEFAULT NULL,
                              `BALTRAANAG` decimal(1,0) DEFAULT NULL,
                              `CCODICECONSORZIO` varchar(6) DEFAULT NULL,
                              `IDLINGUA` decimal(18,0) DEFAULT NULL,
                              `DDECESSO` date DEFAULT NULL,
                              `IDRESIDENCE` decimal(18,0) DEFAULT NULL,
                              `IDBIRTHADDRESS` decimal(18,0) DEFAULT NULL,
                              `CLOCKREASON` varchar(255) DEFAULT NULL,
                              `BFORZATOCF` decimal(1,0) DEFAULT NULL,
                              PRIMARY KEY (`IDSOGGETTO`,`IDDATISINGOLI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `paindirizzo` (
                               `IDINDIRIZZO` decimal(18,0) NOT NULL,
                               `CPROVINCIA` varchar(4) DEFAULT NULL,
                               `CCAP` varchar(5) DEFAULT NULL,
                               `IDTOPONIMO` decimal(18,0) DEFAULT NULL,
                               `CSIGLANAZIONE` varchar(3) DEFAULT NULL,
                               `CNUMEROCIVICO` varchar(50) DEFAULT NULL,
                               `CCOMUNE` varchar(50) DEFAULT NULL,
                               `CINDIRIZZO` varchar(150) DEFAULT NULL,
                               `CFRAZIONE` varchar(50) DEFAULT NULL,
                               `CPRESSO` varchar(50) DEFAULT NULL,
                               `BFORZATOINDIRIZZO` decimal(1,0) DEFAULT NULL,
                               `BNORMALIZZATO` decimal(1,0) DEFAULT NULL,
                               `CCAB` varchar(6) DEFAULT NULL,
                               `BPRINCIPALE` decimal(1,0) DEFAULT NULL,
                               `CCODICE` varchar(10) DEFAULT NULL,
                               `CLATITUDINE` varchar(30) DEFAULT NULL,
                               `CLONGITUDINE` varchar(30) DEFAULT NULL,
                               `CCODEDETTAGLIO` varchar(6) DEFAULT NULL,
                               `CCODICEISTAT` varchar(6) DEFAULT NULL,
                               `CCOMUNEESTERO` varchar(150) DEFAULT NULL,
                               PRIMARY KEY (`IDINDIRIZZO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `padatisingoli` (
                                 `IDDATISINGOLI` decimal(18,0) NOT NULL,
                                 `CPARTITAIVA` varchar(11) DEFAULT NULL,
                                 `CDENOMINAZIONE` varchar(150) DEFAULT NULL,
                                 `CNOME` varchar(150) DEFAULT NULL,
                                 `CCOGNOME` varchar(150) DEFAULT NULL,
                                 `IDPROFESSIONE` decimal(18,0) DEFAULT NULL,
                                 `EPRIVACY` decimal(5,0) DEFAULT NULL,
                                 `DCONSENSOPRIVACY` date DEFAULT NULL,
                                 `ESTATOCIVILE` decimal(10,0) DEFAULT NULL,
                                 `CCITTADINANZA` varchar(3) DEFAULT NULL,
                                 `IDSETTOREATTIVITA` decimal(18,0) DEFAULT NULL,
                                 `IDFORMASOC` decimal(18,0) DEFAULT NULL,
                                 `ESTATOANTITERRORIS` decimal(5,0) DEFAULT NULL,
                                 `IDSOTTOGRUPPO` decimal(18,0) DEFAULT NULL,
                                 `IDGRUPPO` decimal(18,0) DEFAULT NULL,
                                 `DINGRESSOINITALIA` date DEFAULT NULL,
                                 `ETIPOCLIENTE` decimal(5,0) DEFAULT NULL,
                                 `CCONTOCLIENTE` varchar(30) DEFAULT NULL,
                                 `CCONTOFORNITORE` varchar(30) DEFAULT NULL,
                                 `NPERCRITENACC` decimal(9,6) DEFAULT NULL,
                                 `IDCODATECO` decimal(18,0) DEFAULT NULL,
                                 `CORIGINALSURNAME` varchar(150) DEFAULT NULL,
                                 `CORIGINALNAME` varchar(150) DEFAULT NULL,
                                 `CORIGCOMPANYNAME` varchar(150) DEFAULT NULL,
                                 `NPUBLICSHARE` decimal(9,6) DEFAULT NULL,
                                 `NWORKERSHARE` decimal(9,6) DEFAULT NULL,
                                 `CSECTORNOTE` varchar(255) DEFAULT NULL,
                                 `BGROUP` decimal(1,0) DEFAULT NULL,
                                 `IDGROUPTYPE` decimal(18,0) DEFAULT NULL,
                                 `CCOMMERCIALNAME` varchar(150) DEFAULT NULL,
                                 `EFRANCHISINGQUAL` decimal(18,0) DEFAULT NULL,
                                 `BPOLITICALLYEXP` decimal(1,0) DEFAULT NULL,
                                 `BINREGISTRATION` decimal(1,0) DEFAULT NULL,
                                 `EMATRIMONIALARRANG` decimal(18,0) DEFAULT NULL,
                                 `DCOUNTERTERRORISM` date DEFAULT NULL,
                                 `CBIRTHNAME` varchar(150) DEFAULT NULL,
                                 `NSALAREDWORKERS` decimal(6,0) DEFAULT NULL,
                                 `BVARIABLECAPITAL` decimal(1,0) DEFAULT NULL,
                                 `NSHARECAPITAL` decimal(17,3) DEFAULT NULL,
                                 `IDCURRENCY` decimal(5,0) DEFAULT NULL,
                                 `ECODFAMIGLIA` decimal(5,0) DEFAULT NULL,
                                 `CNDG` varchar(30) DEFAULT NULL,
                                 `CRAMOATTIVITA` varchar(50) DEFAULT NULL,
                                 `CSUBGRPATTIVITA` varchar(50) DEFAULT NULL,
                                 `CCODATECO` varchar(50) DEFAULT NULL,
                                 `DISCRIZIONEREGIMPRESE` date DEFAULT NULL,
                                 `DINIZIOATTIVITAREGIMPRESE` date DEFAULT NULL,
                                 `NFATTURATO` decimal(16,2) DEFAULT NULL,
                                 `NDIPENDENTI` decimal(10,0) DEFAULT NULL,
                                 `NRETRIBUZIONI2010` decimal(16,2) DEFAULT NULL,
                                 `NECID` decimal(18,0) DEFAULT NULL,
                                 `CCODSAECOMMANDER` varchar(50) DEFAULT NULL,
                                 PRIMARY KEY (`IDDATISINGOLI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `pcruolo` (
                           `idruolo` int(11) NOT NULL,
                           `cruolo` int(11) DEFAULT NULL,
                           `idsoggettolock` int(11) DEFAULT NULL,
                           PRIMARY KEY (`idruolo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `vttab022` (
                            `T022_CODSOC` int(11) NOT NULL,
                            `T022_CATEGORIA` char(2) NOT NULL,
                            `T022_AGENZIA` char(6) NOT NULL,
                            `T022_NUM_COLL` int(11) NOT NULL,
                            `T022_NUM_POLIZZA` int(11) NOT NULL,
                            `T022_STATO` char(1) DEFAULT NULL,
                            `T022_CAUSALE` char(2) DEFAULT NULL,
                            `T022_DATA_CREAZ` date DEFAULT NULL,
                            `T022_USER_CREAZ` char(6) DEFAULT NULL,
                            `T022_PRODOTTO` char(10) DEFAULT NULL,
                            `T022_NUMERO_UT` smallint(6) DEFAULT NULL,
                            `T022_AGENZIA_GEST` char(6) DEFAULT NULL,
                            `T022_SUBAGENTE` char(10) DEFAULT NULL,
                            `T022_CONVENZIONE` char(10) DEFAULT NULL,
                            `T022_DECORRENZA` date DEFAULT NULL,
                            `T022_DURATA` decimal(4,2) DEFAULT NULL,
                            `T022_SCADENZA` date DEFAULT NULL,
                            `T022_COD_CONTR` int(11) DEFAULT NULL,
                            `T022_COD_ASSIC` int(11) DEFAULT NULL,
                            `T022_COD_ASSIC2` int(11) DEFAULT NULL,
                            `T022_COD_BENV1` int(11) DEFAULT NULL,
                            `T022_COD_BENV2` int(11) DEFAULT NULL,
                            `T022_COD_BENV3` int(11) DEFAULT NULL,
                            `T022_COD_BENV4` int(11) DEFAULT NULL,
                            `T022_COD_BENV5` int(11) DEFAULT NULL,
                            `T022_COD_BENM1` int(11) DEFAULT NULL,
                            `T022_COD_BENM2` int(11) DEFAULT NULL,
                            `T022_COD_BENM3` int(11) DEFAULT NULL,
                            `T022_COD_BENM4` int(11) DEFAULT NULL,
                            `T022_COD_BENM5` int(11) DEFAULT NULL,
                            `T022_NOMINATIVO` char(30) DEFAULT NULL,
                            `T022_SPESE_MEDICHE` int(11) DEFAULT NULL,
                            `T022_COSTO_POLIZZA` int(11) DEFAULT NULL,
                            `T022_COSTO_QUIET` int(11) DEFAULT NULL,
                            `T022_LIBERO` int(11) DEFAULT NULL,
                            `T022_PREVENTIVO` int(11) DEFAULT NULL,
                            `T022_COD_DIVISA` char(10) DEFAULT NULL,
                            `T022_ESENTASSE` char(1) DEFAULT NULL,
                            `T022_PREMI_RICORR` char(1) DEFAULT NULL,
                            `T022_PERIODICITA` smallint(6) DEFAULT NULL,
                            `T022_NUMERO_PROP` int(11) DEFAULT NULL,
                            `T022_DATA_VARIAZ` date DEFAULT NULL,
                            `T022_ULT_PROG_ST` smallint(6) DEFAULT NULL,
                            `T022_STATISTICO1` char(10) DEFAULT NULL,
                            `T022_STATISTICO2` char(10) DEFAULT NULL,
                            `T022_STATISTICO3` char(10) DEFAULT NULL,
                            `T022_STATISTICO4` char(10) DEFAULT NULL,
                            `T022_SESSO` char(1) DEFAULT NULL,
                            `T022_SESSO2` char(1) DEFAULT NULL,
                            `T022_DECORR_PUR` date DEFAULT NULL,
                            `T022_ULTPOS_PUR` smallint(6) DEFAULT NULL,
                            `T022_AGENZIA_PROP` char(6) DEFAULT NULL,
                            `T022_TIPO_RIV` char(1) DEFAULT NULL,
                            `T022_COD_COMPAGNIA` char(3) DEFAULT NULL,
                            `T022_COD_MATRICOLA` char(12) DEFAULT NULL,
                            `T022_LIBERO_F1` char(1) DEFAULT NULL,
                            `T022_LIBERO_F2` char(1) DEFAULT NULL,
                            `T022_LIBERO_F3` char(1) DEFAULT NULL,
                            `T022_LIBERO_F4` char(1) DEFAULT NULL,
                            `T022_LIBERO_F5` char(1) DEFAULT NULL,
                            `T022_LIBERO_D1` date DEFAULT NULL,
                            `T022_LIBERO_D2` date DEFAULT NULL,
                            `T022_COD_SCONTO` char(5) DEFAULT NULL,
                            `T022_LIBERO_A2` char(5) DEFAULT NULL,
                            `T022_LIBERO_A3` char(10) DEFAULT NULL,
                            `T022_LIBERO_A4` char(10) DEFAULT NULL,
                            `T022_NUM_APPENDICE` int(11) DEFAULT NULL,
                            `T022_LIBERO_N2` int(11) DEFAULT NULL,
                            `T022_NOMIN_ASS` char(30) DEFAULT NULL,
                            `T022_FONDO` smallint(6) DEFAULT NULL,
                            `T022_FLAG` char(1) DEFAULT NULL,
                            `T022_VALCOMPL` decimal(14,3) DEFAULT NULL,
                            `T022_VALATT` decimal(14,3) DEFAULT NULL,
                            `T022_UL_FONDO` char(10) NOT NULL DEFAULT '',
                            `T022_EMISSIONE` date NOT NULL DEFAULT current_timestamp(),
                            `T022_COD_LRAPP1` int(11) NOT NULL DEFAULT 0,
                            `T022_COD_LRAPP2` int(11) NOT NULL DEFAULT 0,
                            PRIMARY KEY (`T022_CODSOC`,`T022_CATEGORIA`,`T022_AGENZIA`,`T022_NUM_COLL`,`T022_NUM_POLIZZA`),
                            UNIQUE KEY `VTI00221` (`T022_CODSOC`,`T022_CATEGORIA`,`T022_AGENZIA`,`T022_NUM_COLL`,`T022_NUM_POLIZZA`),
                            KEY `VTI00225` (`T022_NUM_POLIZZA`,`T022_AGENZIA_PROP`,`T022_NUM_COLL`,`T022_CODSOC`),
                            KEY `VTI00224` (`T022_COD_ASSIC`,`T022_CODSOC`),
                            KEY `AVVT0221` (`T022_NUMERO_PROP`,`T022_AGENZIA_PROP`,`T022_CODSOC`),
                            KEY `VTI00223` (`T022_NOMIN_ASS`),
                            KEY `VTI00222` (`T022_NOMINATIVO`),
                            KEY `AAVT2009` (`T022_COD_CONTR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `vttab024` (
                            `T024_CODSOC` int(11) NOT NULL,
                            `T024_CATEGORIA` char(2) NOT NULL,
                            `T024_AGENZIA` char(6) NOT NULL,
                            `T024_NUM_COLL` int(11) NOT NULL,
                            `T024_NUM_POLIZZA` int(11) NOT NULL,
                            `T024_POSIZIONE` smallint(6) NOT NULL,
                            `T024_STATO` char(1) DEFAULT NULL,
                            `T024_CAUSALE` char(2) DEFAULT NULL,
                            `T024_DATA_CREAZ` date DEFAULT NULL,
                            `T024_USER_CREAZ` char(6) DEFAULT NULL,
                            `T024_CODICE_UT` char(10) DEFAULT NULL,
                            `T024_EMISSIONE` date DEFAULT NULL,
                            `T024_DECORRENZA` date DEFAULT NULL,
                            `T024_DURATA` decimal(4,2) DEFAULT NULL,
                            `T024_SCADENZA` date DEFAULT NULL,
                            `T024_CONVENZIONE` char(10) DEFAULT NULL,
                            `T024_AGENZ_ACQUIS` char(6) DEFAULT NULL,
                            `T024_AGENZIA_GEST` char(6) DEFAULT NULL,
                            `T024_SUBAGENTE` char(6) DEFAULT NULL,
                            `T024_VISITA_MEDICA` char(1) DEFAULT NULL,
                            `T024_SPESE_MEDICHE` decimal(11,2) DEFAULT NULL,
                            `T024_COSTO_POLIZZA` decimal(11,2) DEFAULT NULL,
                            `T024_COSTO_QUIET` decimal(11,2) DEFAULT NULL,
                            `T024_DATA_TR_COASS` date DEFAULT NULL,
                            `T024_TRATT_COASS` char(10) DEFAULT NULL,
                            `T024_DATA_TR_RIASS` date DEFAULT NULL,
                            `T024_TRATT_RIASS` char(10) DEFAULT NULL,
                            `T024_FONDO_RIVALUT` int(11) DEFAULT NULL,
                            `T024_TIPO_PREMIO` char(1) DEFAULT NULL,
                            `T024_TIPO_PREMIO2` char(1) DEFAULT NULL,
                            `T024_FRAZ_PREMIO` smallint(6) DEFAULT NULL,
                            `T024_PREMIO_RATA` decimal(14,3) DEFAULT NULL,
                            `T024_INT_FRAZ` decimal(4,2) DEFAULT NULL,
                            `T024_PREMIO_NETTO` decimal(14,3) DEFAULT NULL,
                            `T024_PRESTAZIONE` decimal(14,3) DEFAULT NULL,
                            `T024_PREST_RIV` decimal(14,3) DEFAULT NULL,
                            `T024_FRAZ_RENDITA` smallint(6) DEFAULT NULL,
                            `T024_CAP_OPZIONE` decimal(14,3) DEFAULT NULL,
                            `T024_PREMIO_PURO` decimal(14,3) DEFAULT NULL,
                            `T024_PREMIO_INVENT` decimal(14,3) DEFAULT NULL,
                            `T024_PREMIO_TARIFF` decimal(14,3) DEFAULT NULL,
                            `T024_ULT_PRE_PURO` decimal(14,3) DEFAULT NULL,
                            `T024_ULT_PRE_TARIF` decimal(14,3) DEFAULT NULL,
                            `T024_DUR_PAG_P_UN` decimal(4,2) DEFAULT NULL,
                            `T024_ABI` char(5) DEFAULT NULL,
                            `T024_CAB` char(5) DEFAULT NULL,
                            `T024_ULT_PRE_INVEN` decimal(14,3) DEFAULT NULL,
                            `T024_CONTO_CORR` char(20) DEFAULT NULL,
                            `T024_DEFISC` char(1) DEFAULT NULL,
                            `T024_RATEO_INIZ` decimal(2,0) DEFAULT NULL,
                            `T024_PREMIO_LIM` decimal(2,0) DEFAULT NULL,
                            `T024_Q_CARICO_ASS` decimal(14,3) DEFAULT NULL,
                            `T024_DATA_VARIAZ` date DEFAULT NULL,
                            `T024_ULT_PROG_ST` smallint(6) DEFAULT NULL,
                            `T024_ETA` decimal(4,2) DEFAULT NULL,
                            `T024_PREMIO_SUCC` decimal(14,3) DEFAULT NULL,
                            `T024_NEXT_QUIET_P` date DEFAULT NULL,
                            `T024_NEXT_QUIET_R` date DEFAULT NULL,
                            `T024_DATA_RIVAL` date DEFAULT NULL,
                            `T024_DATA_Q_INC` date DEFAULT NULL,
                            `T024_ANNO_FRAZ` smallint(6) DEFAULT NULL,
                            `T024_NUOVO_FRAZ` smallint(6) DEFAULT NULL,
                            `T024_TIPO_GAR` char(1) DEFAULT NULL,
                            `T024_APPENDICE` smallint(6) DEFAULT NULL,
                            `T024_PERC_IMPOSTE` decimal(4,2) DEFAULT NULL,
                            `T024_PERC_INA` decimal(4,2) DEFAULT NULL,
                            `T024_ABBUONO_TOT` decimal(14,3) DEFAULT NULL,
                            `T024_ABBUONO_ANNUO` decimal(14,3) DEFAULT NULL,
                            `T024_ANNI_ABBUONO` smallint(6) DEFAULT NULL,
                            `T024_DATE_TIME` decimal(11,0) DEFAULT NULL,
                            `T024_STATISTICO1` char(10) DEFAULT NULL,
                            `T024_STATISTICO2` char(10) DEFAULT NULL,
                            `T024_STATISTICO3` char(10) DEFAULT NULL,
                            `T024_STATISTICO4` char(10) DEFAULT NULL,
                            `T024_TIPO_RISCATTO` char(1) DEFAULT NULL,
                            `T024_DECRESCENZA` smallint(6) DEFAULT NULL,
                            `T024_BONUS` decimal(14,3) DEFAULT NULL,
                            `T024_RIPARTO_RIASS` char(1) DEFAULT NULL,
                            `T024_DATA_PERFEZ` date DEFAULT NULL,
                            `T024_TIPO_SCONTO` char(1) DEFAULT NULL,
                            `T024_RISTAMPA` char(1) DEFAULT NULL,
                            `T024_CESSIONE_CIRT` char(1) DEFAULT NULL,
                            `T024_SCADENZA_ANT` char(1) DEFAULT NULL,
                            `T024_MODAL_PAGAM` char(1) DEFAULT NULL,
                            `T024_LIBERO_D1` date DEFAULT NULL,
                            `T024_LIBERO_D2` date DEFAULT NULL,
                            `T024_IMP_SCONTO` decimal(14,3) DEFAULT NULL,
                            `T024_LIBERO_I2` decimal(14,3) DEFAULT NULL,
                            `T024_LIBERO_A1` char(5) DEFAULT NULL,
                            `T024_COD_CLASSIF` char(5) DEFAULT NULL,
                            `T024_LIBERO_A3` char(10) DEFAULT NULL,
                            `T024_LIBERO_A4` char(10) DEFAULT NULL,
                            `T024_NUM_APPENDICE` int(11) DEFAULT NULL,
                            `T024_SOPRAMORT` int(11) DEFAULT NULL,
                            `T024_CARENZA_MM` smallint(6) DEFAULT NULL,
                            `T024_LIBERO_N4` smallint(6) DEFAULT NULL,
                            `T024_PRESTA_AGG` decimal(14,3) DEFAULT NULL,
                            `T024_PRESTA_AGG_I` decimal(14,3) DEFAULT NULL,
                            `T024_COMBINATA` char(1) DEFAULT NULL,
                            `T024_PERC_ABB_PROV` decimal(5,2) DEFAULT NULL,
                            `T024_PREMI_RICORR` char(1) DEFAULT '',
                            `T024_UL_FONDO` char(10) DEFAULT '',
                            `T024_UL_TIPORIC` char(1) DEFAULT '',
                            `T024_UL_DATESTR` date DEFAULT current_timestamp(),
                            `T024_UL_DATAGGQ` date DEFAULT current_timestamp(),
                            `T024_BIC` char(11) DEFAULT '',
                            `T024_IBAN_ID_PAE` char(2) DEFAULT '',
                            `T024_IBAN_CIN_PAE` char(2) DEFAULT '',
                            `T024_IBAN_CIN_CONTO` char(1) DEFAULT '',
                            `T024_COD_PTF` char(10) DEFAULT '',
                            PRIMARY KEY (`T024_CODSOC`,`T024_CATEGORIA`,`T024_AGENZIA`,`T024_NUM_COLL`,`T024_NUM_POLIZZA`,`T024_POSIZIONE`),
                            UNIQUE KEY `VTI00241` (`T024_CODSOC`,`T024_CATEGORIA`,`T024_AGENZIA`,`T024_NUM_COLL`,`T024_NUM_POLIZZA`,`T024_POSIZIONE`),
                            KEY `AVVT0242` (`T024_NUM_POLIZZA`,`T024_NUM_COLL`,`T024_DECORRENZA`,`T024_CODICE_UT`,`T024_AGENZIA`,`T024_CATEGORIA`,`T024_CODSOC`),
                            KEY `VTI00243` (`T024_CODSOC`,`T024_COD_PTF`),
                            KEY `VTI00242` (`T024_CODSOC`,`T024_UL_FONDO`,`T024_UL_DATAGGQ`,`T024_TIPO_GAR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `vttab200` (
                            `T200_CODCLI` int(11) NOT NULL,
                            `T200_CODFISC` char(16) DEFAULT NULL,
                            `T200_NOMINATIVO` char(30) DEFAULT NULL,
                            `T200_INDIRIZZO` char(30) DEFAULT NULL,
                            `T200_LOCALITA` char(30) DEFAULT NULL,
                            `T200_CAP` int(11) DEFAULT NULL,
                            `T200_PROVINCIA` char(2) DEFAULT NULL,
                            `T200_NAZIONE` char(3) DEFAULT NULL,
                            `T200_NATO` date DEFAULT NULL,
                            `T200_SESSO` char(1) DEFAULT NULL,
                            `T200_PROFESSIONE` char(10) DEFAULT NULL,
                            `T200_CODCUSTOMER` int(11) DEFAULT NULL,
                            `T200_FLAG` char(1) DEFAULT NULL,
                            `T200_CODSOC` int(11) NOT NULL,
                            `T200_TIPO_RELAZ` char(1) DEFAULT NULL,
                            `T200_CODICE_RELAZ` char(25) DEFAULT NULL,
                            `T200_LOCALITA_EX` char(30) DEFAULT NULL,
                            `T200_PROVINCIA_EX` char(2) DEFAULT NULL,
                            `T200_NUM_DOC_EX` char(12) DEFAULT NULL,
                            `T200_TIPO_DOC_EX` char(2) DEFAULT NULL,
                            `T200_RILASCIO_EX` char(10) DEFAULT NULL,
                            `T200_INFO1_EX` char(30) DEFAULT NULL,
                            `T200_INFO2_EX` char(30) DEFAULT NULL,
                            `T200_LOCRIL_EX` char(20) DEFAULT NULL,
                            `T200_ENTERIL_EX` char(20) DEFAULT NULL,
                            `T200_NOTE` char(50) DEFAULT NULL,
                            `T200_INDIRIZZO_D` char(30) DEFAULT NULL,
                            `T200_LOCALITA_D` char(30) DEFAULT NULL,
                            `T200_CAP_D` char(5) DEFAULT NULL,
                            `T200_PROVINCIA_D` char(2) DEFAULT NULL,
                            `T200_NAZIONE_D` char(3) DEFAULT NULL,
                            `T200_CC_CEDOLA` char(20) DEFAULT '',
                            `T200_CAB_EX` int(11) DEFAULT NULL,
                            `T200_GRUPPO_EX` char(3) DEFAULT NULL,
                            `T200_SOTTGRUPPO_EX` char(3) DEFAULT NULL,
                            `T200_TELEFONO` char(20) DEFAULT NULL,
                            `T200_PRESSO_D` char(35) DEFAULT NULL,
                            `T200_FORZFISC` char(1) DEFAULT NULL,
                            `T200_STORICO` char(1) DEFAULT NULL,
                            `T200_PERSONA_FIS` char(1) DEFAULT '',
                            `T200_STATO_CIVILE` char(1) DEFAULT '',
                            `T200_NUMERO_FIGLI` decimal(1,0) DEFAULT 0,
                            `T200_TITOLO` char(15) DEFAULT '',
                            `T200_TELUFF` char(20) DEFAULT '',
                            `T200_CELL` char(20) DEFAULT '',
                            `T200_FAX` char(20) DEFAULT '',
                            `T200_CAB_D` char(5) DEFAULT '',
                            `T200_PRIVACY` char(1) DEFAULT '',
                            `T200_ABI_CEDOLA` char(5) DEFAULT '',
                            `T200_CAB_CEDOLA` char(5) DEFAULT '',
                            `T200_FIRMA_DBS` char(2) DEFAULT '',
                            `T200_BIC` char(11) DEFAULT '',
                            `T200_IBAN_ID_PAE` char(2) DEFAULT '',
                            `T200_IBAN_CIN_PAE` char(2) DEFAULT '',
                            `T200_IBAN_CIN_CONTO` char(1) DEFAULT '',
                            `T200_FLG_CUSTOMER` char(1) DEFAULT '',
                            `T200_FLG_COMMANDER` char(1) DEFAULT '',
                            `T200_CODCOMMANDER` decimal(11,0) NOT NULL DEFAULT 0,
                            PRIMARY KEY (`T200_CODCLI`,`T200_CODSOC`),
                            UNIQUE KEY `VTI02001` (`T200_CODSOC`,`T200_CODCLI`),
                            KEY `VTI02004` (`T200_CODCUSTOMER`,`T200_CODSOC`),
                            KEY `AVVT2001` (`T200_NOMINATIVO`,`T200_CODFISC`,`T200_NATO`,`T200_LOCALITA_EX`),
                            KEY `VTI02003` (`T200_CODFISC`,`T200_CODSOC`),
                            KEY `VTI02002` (`T200_NOMINATIVO`,`T200_CODCLI`,`T200_CODSOC`),
                            KEY `AAVT2002` (`T200_CODICE_RELAZ`,`T200_PRIVACY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `vttab201` (
                            `T201_CODSOC` int(11) NOT NULL DEFAULT 0,
                            `T201_CODCLI` int(11) NOT NULL DEFAULT 0,
                            `T201_COGNOME` char(30) DEFAULT '',
                            `T201_NOME` char(30) DEFAULT '',
                            `T201_MAIL` char(100) DEFAULT '',
                            `T201_NDG` decimal(9,0) DEFAULT 0,
                            `T201_ABI` char(5) DEFAULT '',
                            `T201_FLG_STORICO` char(1) DEFAULT '',
                            `T201_FLG_PEC` char(1) DEFAULT '',
                            `T201_COD_ATECO` char(6) DEFAULT '',
                            `T201_ISTAT` int(11) DEFAULT 0,
                            `T201_FLG_TEFF` char(1) DEFAULT '',
                            `T201_FLG_FORZ_RES` char(1) DEFAULT '',
                            `T201_FLG_FORZ_DOM` char(1) DEFAULT '',
                            `T201_DATA_OPER` date DEFAULT current_timestamp(),
                            `T201_USER_OPER` char(6) DEFAULT '',
                            `T201_DATA_VAR` date DEFAULT current_timestamp(),
                            `T201_USER_VAR` char(6) DEFAULT '',
                            `T201_TAE` char(3) DEFAULT '',
                            `T201_COD_CITTADIN` decimal(3,0) DEFAULT 0,
                            `T201_DES_CITTADIN` char(3) DEFAULT '',
                            `T201_RES_FISCALE` char(3) DEFAULT '',
                            `T201_DES_RES_FISCALE` char(3) DEFAULT '',
                            `T201_COD_UIC_RES` char(3) DEFAULT '',
                            `T201_COD_UIC_DOM` char(3) DEFAULT '',
                            `T201_DT_SCAD_DOC_EX` date DEFAULT current_timestamp(),
                            `T201_DICH_PEP` char(2) DEFAULT '',
                            `T201_TIP_SOCIETA` char(2) DEFAULT '',
                            `T201_TIP_SOCIETA_NOTE` char(200) DEFAULT '',
                            `T201_RELAZ_FIG` char(2) DEFAULT '',
                            `T201_RELAZ_FIG_NOTE` char(120) DEFAULT '',
                            `T201_VARBEN_LEG_CC` char(2) DEFAULT '',
                            `T201_BEN_TIPO_NOM` char(1) DEFAULT '',
                            `T201_POLITICO_LOCALE` char(2) DEFAULT '',
                            `T201_CARICA_POLITICO_LOC` char(2) DEFAULT '',
                            `T201_INQUADRAMENTO` char(2) DEFAULT '',
                            `T201_ULTIMA_ATTIVITA` char(10) DEFAULT '',
                            `T201_DATA_COSTITUZIONE` date DEFAULT current_timestamp(),
                            `T201_COD_FISCALE_SOC` char(11) DEFAULT '',
                            `T201_SETTORE_ECONOMICO` char(2) DEFAULT '',
                            `T201_INFO_AGG_SOC` char(2) DEFAULT '',
                            `T201_AREA_GEO_ATTIVITA` char(2) DEFAULT '',
                            `T201_AREA_GEO_PROV` char(2) DEFAULT '',
                            `T201_AREA_GEO_LOCALITA` char(30) DEFAULT '',
                            `T201_AREA_GEO_CAP` char(5) DEFAULT '',
                            `T201_NAZ_EST_ATTIVITA` char(3) DEFAULT '',
                            `T201_ESISTE_LRAPP` char(2) DEFAULT '',
                            `T201_RELAZ_FIG_TIPO` char(2) DEFAULT '',
                            `T201_DOCUMENT_RACC` char(2) DEFAULT '',
                            `T201_FLG_NO_COMUNICAZ` char(2) DEFAULT '',
                            `T201_CONTR_PA` char(2) DEFAULT '',
                            `T201_PEP_TER` char(3) DEFAULT '',
                            PRIMARY KEY (`T201_CODSOC`,`T201_CODCLI`),
                            UNIQUE KEY `VTI02011` (`T201_CODSOC`,`T201_CODCLI`),
                            KEY `VTI02012` (`T201_CODSOC`,`T201_ABI`,`T201_NDG`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE NOMECOGNOME (
                             ID INT PRIMARY KEY AUTO_INCREMENT,
                             NOME VARCHAR(20) NOT NULL,
                             COGNOME VARCHAR(20)  NOT NULL,
                             USATO BOOLEAN not null DEFAULT false,
                             UNIQUE(NOME, COGNOME)
);
CREATE TABLE NOMI (
    NOME VARCHAR(20)  PRIMARY KEY
);
CREATE TABLE COGNOMI(
    COGNOME VARCHAR(20)  PRIMARY KEY
);