CREATE TABLE NOMECOGNOME (
ID INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(20) NOT NULL,
COGNOME VARCHAR(20)  NOT NULL,
USATO BOOLEAN not null DEFAULT false,
UNIQUE(NOME, COGNOME)
);
CREATE TABLE NOMI (
NOME VARCHAR(20)  PRIMARY KEY
);
CREATE TABLE COGNOMI(
COGNOME VARCHAR(20)  PRIMARY KEY
);
