CREATE TABLE NOMECOGNOME (
ID INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(20) NOT NULL,
COGNOME VARCHAR(20)  NOT NULL,
USATO BOOLEAN not null DEFAULT false,
UNIQUE(NOME, COGNOME)
);
CREATE TABLE NOMI (
NOME VARCHAR(20)  PRIMARY KEY
);
CREATE TABLE COGNOMI(
COGNOME VARCHAR(20)  PRIMARY KEY
);
INSERT INTO NOMI VALUES ('mario');
INSERT INTO NOMI VALUES ('giacomo');
INSERT INTO NOMI VALUES ('roberto');
INSERT INTO COGNOMI VALUES ('rossi');
INSERT INTO COGNOMI VALUES ('verdi');
INSERT INTO COGNOMI VALUES ('gialli');
