INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Abaco');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Abbondio');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Abelardo');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Abenzio');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Abramio');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Acacio');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Accursio');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Acilio');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Acrisio');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Adalberto');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Adalgiso');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Adamo');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Adelardo');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Adelchi');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Adelgardo');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Adeodato');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Adone');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Adrione');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Agabio');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Agapito');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Agenore');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Agostino');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Aiace');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Aimone');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Alamanno');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Alarico');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Alberico');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Albino');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Albrico');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Alceste');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Alcide');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Aldo');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Aleandro');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Aleramo');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Alessio');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Alfonso');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Algiso');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Almerigo');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Aloisio');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Alviero');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Amabile');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Amando');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Amaranto');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Amatore');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Ambrogio');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Amedeo');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Amerigo');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Amilcare');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Amleto');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Amore');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Ampelio');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Andrea');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Aniceto');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Annibale');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Anselmo');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Antelmo');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Antimo');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Antioco');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Antonio');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Apollo');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Aquilino');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Aratone');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Archimede');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Arcibaldo');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Arduino');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Argimiro');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Arialdo');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Ariele');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Aris');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Aristeo');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Aristione');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Aristofane');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Armando');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Arnaldo');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Arrigo');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Ascanio');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Asimodeo');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Asterio');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Ataleo');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Athos');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Attilano');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Auberto');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Augusto');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Aurelio');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Ausilio');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Azeglio');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Manuele');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Marciano');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Mariano');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Mario');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Martino');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Massimiliano');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Matroniano');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Mattia');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Maurizio');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Medardo');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Melanio');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Melchiorre');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Menardo');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Meneo');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Anna');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Macaria');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Mafalda');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Maida');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Mara');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Marcella');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Margherita');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Marianna');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Mariella');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Marina');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Marinetta');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Marita');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Martina');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Marzia');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Matilde');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Melania');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Melitina');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Mercede');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Mia');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Milena');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Mina');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Minervina');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Mirella');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Mirta');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Monica');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Morgana');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Lara');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Lavinia');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Leda');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Lena');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Leonilda');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Letizia');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Liana');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Liboria');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Lidania');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Liliana');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Lisa');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Liviana');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Loredana');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Lorena');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Loretta');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Luana');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Lucia');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Lucilla');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Ludovica');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Luisa');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Luna');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Laura');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Lea');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Lelia');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Leonia');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Leontina');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Lia');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Liberata');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Licia');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Lidia');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Linda');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Livia');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Lodovica');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Lorella');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Lorenza');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Loriana');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Luce');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Luciana');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Lucrezia');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Luigia');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Luminosa');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Fabiana');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Fatima');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Federica');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Felicia');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Fernanda');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Filippa');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Fiordaliso');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Fiorella');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Flaminia');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Flaviana');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Floriana');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Florina');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Fortunata');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Franca');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Fulvia');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Fabiola');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Fausta');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Fedora');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Felicita');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Fiammetta');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Filomena');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Fiore');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Fiorenza');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Flavia');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Flora');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Floridia');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Foca');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Fosca');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Francesca');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Calogera');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Camelia');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Candida');
INSERT INTO `datalakearca`.`nomi` (`nome`) VALUES ('Carina');







INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Rossi	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Ferrari	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Russo	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Bianchi	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Romano	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Gallo	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Costa	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Fontana	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Conti	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Esposito	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Ricci	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Bruno	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Rizzo	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Moretti	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Marino	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Greco	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Barbieri	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Lombardi	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Giordano	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Rinaldi	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Colombo	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Mancini	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Longo	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Leone	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Martinelli	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Marchetti	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Martini	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Galli	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Gatti	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Mariani	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Ferrara	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Santoro	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Marini	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Bianco	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Conte	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Serra	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Farina	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Gentile	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Caruso	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Morelli	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Ferri	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Testa	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Ferraro	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Pellegrini	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Grassi	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Rossetti	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	D''Angelo	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Bernardi	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Mazza	');
INSERT INTO `datalakearca`.`cognomi` (`cognome`) VALUES ('	Rizzi	');


